# Getting Financial Data - Pandas Datareader

### Introduction:

This time you will get data from a website.


### Step 1. Import the necessary libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import pandas_datareader.data as web
import datetime as dt

### Step 2. Create your time range (start and end variables). The start date should be 01/01/2015 and the end should today (whatever your today is).

In [2]:
start = dt.datetime(2015, 1, 1)
end = dt.datetime.today()
end

datetime.datetime(2026, 4, 20, 21, 12, 28, 469811)

### Step 3. Get an API key for one of the APIs that are supported by Pandas Datareader, preferably for AlphaVantage.

If you do not have an API key for any of the supported APIs, it is easiest to get one for [AlphaVantage](https://www.alphavantage.co/support/#api-key). (Note that the API key is shown directly after the signup. You do *not* receive it via e-mail.)

(For a full list of the APIs that are supported by Pandas Datareader, [see here](https://pydata.github.io/pandas-datareader/readers/index.html). As the APIs are provided by third parties, this list may change.)

### Step 4. Use Pandas Datarader to read the daily time series for the Apple stock (ticker symbol AAPL) between 01/01/2015 and today, assign it to df_apple and print it.

In [3]:
import yfinance as yf
df_apple = yf.download("AAPL", start=start, end=end)
df_apple.head()

/tmp/ipykernel_19886/1313344283.py:2: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df_apple = yf.download("AAPL", start=start, end=end)
[*********************100%***********************]  1 of 1 completed

Price           Close       High        Low       Open     Volume
Ticker           AAPL       AAPL       AAPL       AAPL       AAPL
Date
2015-01-02  24.214895  24.682228  23.776355  24.671153  212818400
2015-01-05  23.532724  24.064287  23.346678  23.984553  257142000
2015-01-06  23.534937  23.794073  23.173916  23.596952  263188400
2015-01-07  23.864950  23.964618  23.632391  23.743133  160423600
2015-01-08  24.781893  24.839479  24.075357  24.192745  237458000

### Step 5. Add a new column "stock" to the dataframe and add the ticker symbol

In [4]:
df_apple["stock"] = "AAPL"
df_apple.head()

Price           Close       High        Low       Open     Volume stock
Ticker           AAPL       AAPL       AAPL       AAPL       AAPL
Date
2015-01-02  24.214895  24.682228  23.776355  24.671153  212818400  AAPL
2015-01-05  23.532724  24.064287  23.346678  23.984553  257142000  AAPL
2015-01-06  23.534937  23.794073  23.173916  23.596952  263188400  AAPL
2015-01-07  23.864950  23.964618  23.632391  23.743133  160423600  AAPL
2015-01-08  24.781893  24.839479  24.075357  24.192745  237458000  AAPL

### Step 6. Repeat the two previous steps for a few other stocks, always creating a new dataframe: Tesla, IBM and Microsoft. (Ticker symbols TSLA, IBM and MSFT.)

In [5]:
tesla = yf.download("TSLA", start=start, end=end)
tesla["stock"] = "TSLA"
tesla.head()

/tmp/ipykernel_19886/820906076.py:1: FutureWarning: YF.download() has changed argument auto_adjust default to True
  tesla = yf.download("TSLA", start=start, end=end)
[*********************100%***********************]  1 of 1 completed

Price           Close       High        Low       Open    Volume stock
Ticker           TSLA       TSLA       TSLA       TSLA      TSLA
Date
2015-01-02  14.620667  14.883333  14.217333  14.858000  71466000  TSLA
2015-01-05  14.006000  14.433333  13.810667  14.303333  80527500  TSLA
2015-01-06  14.085333  14.280000  13.614000  14.004000  93928500  TSLA
2015-01-07  14.063333  14.318667  13.985333  14.223333  44526000  TSLA
2015-01-08  14.041333  14.253333  14.000667  14.187333  51637500  TSLA

In [6]:
ibm = yf.download("IBM", start=start, end=end)
ibm["stock"] = "IBM"
ibm.head()

/tmp/ipykernel_19886/1847918908.py:1: FutureWarning: YF.download() has changed argument auto_adjust default to True
  ibm = yf.download("IBM", start=start, end=end)
[*********************100%***********************]  1 of 1 completed

Price           Close       High        Low       Open   Volume stock
Ticker            IBM        IBM        IBM        IBM      IBM
Date
2015-01-02  97.566765  98.319322  96.928603  97.115238  5779673   IBM
2015-01-05  96.031548  97.091141  95.838897  97.091141  5104898   IBM
2015-01-06  93.960556  96.302498  93.418724  96.127903  6429448   IBM
2015-01-07  93.346451  94.640840  92.732369  94.640840  4918083   IBM
2015-01-08  95.375343  95.748605  93.647483  94.062889  4431693   IBM

In [7]:
microsoft = yf.download("MSFT", start=start, end=end)
microsoft["stock"] = "MSFT"
microsoft.head()

/tmp/ipykernel_19886/3281817728.py:1: FutureWarning: YF.download() has changed argument auto_adjust default to True
  microsoft = yf.download("MSFT", start=start, end=end)
[*********************100%***********************]  1 of 1 completed

Price           Close       High        Low       Open    Volume stock
Ticker           MSFT       MSFT       MSFT       MSFT      MSFT
Date
2015-01-02  39.767685  40.328991  39.580585  39.682640  27913900  MSFT
2015-01-05  39.401989  39.742173  39.333950  39.436005  39673900  MSFT
2015-01-06  38.823692  39.759202  38.730141  39.444531  36447900  MSFT
2015-01-07  39.316936  39.512543  38.687595  39.104321  29114100  MSFT
2015-01-08  40.473576  40.609650  39.733673  39.759186  29645200  MSFT

### Step 7. Combine the four separate dataFrames into one combined dataFrame df that holds the information for all four stocks

In [8]:
df = pd.concat([df_apple, tesla, ibm, microsoft])
df.head()

Price,Close,High,Low,Open,Volume,stock,Close,High,Low,Open,...,Close,High,Low,Open,Volume,Close,High,Low,Open,Volume
Ticker,AAPL,AAPL,AAPL,AAPL,AAPL,,TSLA,TSLA,TSLA,TSLA,...,IBM,IBM,IBM,IBM,IBM,MSFT,MSFT,MSFT,MSFT,MSFT
Date,,,,,,,,,,,,,,,,,,,,,
2015-01-02,24.214895,24.682228,23.776355,24.671153,212818400.0,AAPL,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-01-05,23.532724,24.064287,23.346678,23.984553,257142000.0,AAPL,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-01-06,23.534937,23.794073,23.173916,23.596952,263188400.0,AAPL,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-01-07,23.864950,23.964618,23.632391,23.743133,160423600.0,AAPL,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-01-08,24.781893,24.839479,24.075357,24.192745,237458000.0,AAPL,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Step 8. Shift the stock column into the index (making it a multi-level index consisting of the ticker symbol and the date).

In [9]:
df.set_index("stock", append=True, inplace=True)
df.head()

,Price,Close,High,Low,Open,Volume,Close,High,Low,Open,Volume,Close,High,Low,Open,Volume,Close,High,Low,Open,Volume
,Ticker,AAPL,AAPL,AAPL,AAPL,AAPL,TSLA,TSLA,TSLA,TSLA,TSLA,IBM,IBM,IBM,IBM,IBM,MSFT,MSFT,MSFT,MSFT,MSFT
Date,stock,,,,,,,,,,,,,,,,,,,,
2015-01-02,AAPL,24.214895,24.682228,23.776355,24.671153,212818400.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-01-05,AAPL,23.532724,24.064287,23.346678,23.984553,257142000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-01-06,AAPL,23.534937,23.794073,23.173916,23.596952,263188400.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-01-07,AAPL,23.864950,23.964618,23.632391,23.743133,160423600.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-01-08,AAPL,24.781893,24.839479,24.075357,24.192745,237458000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Step 7. Create a dataFrame called vol, with the volume values.

In [10]:
vol = df["Volume"]
vol.head()

Ticker                   AAPL  TSLA  IBM  MSFT
Date       stock
2015-01-02 AAPL   212818400.0   NaN  NaN   NaN
2015-01-05 AAPL   257142000.0   NaN  NaN   NaN
2015-01-06 AAPL   263188400.0   NaN  NaN   NaN
2015-01-07 AAPL   160423600.0   NaN  NaN   NaN
2015-01-08 AAPL   237458000.0   NaN  NaN   NaN

### Step 8. Aggregate the data of volume to weekly.
Hint: Be careful to not sum data from the same week of 2015 and other years.

In [13]:
daily_total_volume = vol.sum(axis=1)
df_temp = daily_total_volume.reset_index()
df_temp['year'] = df_temp['Date'].dt.year
df_temp['week'] = df_temp['Date'].dt.isocalendar().week
weekly_vol = df_temp.groupby(['year', 'week'])[0].sum()
weekly_vol

year  week
2015  1       3.179780e+08
      2       1.658058e+09
      3       1.860312e+09
      4       1.208158e+09
      5       2.571403e+09
                  ...
2026  13      7.113354e+08
      14      6.053676e+08
      15      6.871281e+08
      16      8.516843e+08
      17      1.299771e+08
Name: 0, Length: 591, dtype: float64

### Step 9. Find all the volume traded in the year of 2015

In [14]:
volume_2015 = df_temp[df_temp['year'] == 2015][0].sum()
volume_2015

np.float64(78803361900.0)