# Housing Market

### Introduction:

This time we will create our own dataset with fictional numbers to describe a house market. As we are going to create random data don't try to reason of the numbers.

### Step 1. Import the necessary libraries

In [1]:
import pandas as pd
import numpy as np

### Step 2. Create 3 differents Series, each of length 100, as follows:
1. The first a random number from 1 to 4
2. The second a random number from 1 to 3
3. The third a random number from 10,000 to 30,000

In [2]:
first = pd.Series(np.random.randint(1,5,100))
second = pd.Series(np.random.randint(1,4,100))
third = pd.Series(np.random.randint(10000,30000,100))

### Step 3. Let's create a DataFrame by joinning the Series by column

In [3]:
df = pd.concat([first,second,third],axis=1)
df

    0  1      2
0   2  1  28979
1   1  2  28097
2   4  2  12796
3   3  3  14016
4   3  1  20933
.. .. ..    ...
95  2  2  22925
96  4  1  15414
97  4  2  29542
98  2  1  27429
99  4  2  25937

[100 rows x 3 columns]

### Step 4. Change the name of the columns to bedrs, bathrs, price_sqr_meter

In [4]:
df.rename(columns={0:'bedrs',1:'bathrs',2:'price_sqr_meter'},inplace=True)
df

    bedrs  bathrs  price_sqr_meter
0       2       1            28979
1       1       2            28097
2       4       2            12796
3       3       3            14016
4       3       1            20933
..    ...     ...              ...
95      2       2            22925
96      4       1            15414
97      4       2            29542
98      2       1            27429
99      4       2            25937

[100 rows x 3 columns]

### Step 5. Create a one column DataFrame with the values of the 3 Series and assign it to 'bigcolumn'

In [5]:
bigcolumn = pd.concat([first,second,third],axis=0)
bigcolumn = bigcolumn.to_frame()
bigcolumn

        0
0       2
1       1
2       4
3       3
4       3
..    ...
95  22925
96  15414
97  29542
98  27429
99  25937

[300 rows x 1 columns]

### Step 6. Oops, it seems it is going only until index 99. Is it true?

In [ ]:
#yes

### Step 7. Reindex the DataFrame so it goes from 0 to 299

In [6]:
bigcolumn.reset_index(drop=True,inplace=True)
bigcolumn

         0
0        2
1        1
2        4
3        3
4        3
..     ...
295  22925
296  15414
297  29542
298  27429
299  25937

[300 rows x 1 columns]