# Ex -

### Introduction:

This time you will create a data

Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

### Step 1. Import the necessary libraries

In [1]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv).

### Step 3. Assign it to a variable called

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv', sep = '\t')
df

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

#### 1. How to select the 'item_name' column?

In [4]:
item_name_column = df['item_name']
item_name_column.head()

0             Chips and Fresh Tomato Salsa
1                                     Izze
2                         Nantucket Nectar
3    Chips and Tomatillo-Green Chili Salsa
4                             Chicken Bowl
Name: item_name, dtype: object

#### 2. How to select the 'item_name' and 'quantity' columns?

In [5]:
item_name_quantity_columns = df[['item_name', 'quantity']]
item_name_quantity_columns.head()

                               item_name  quantity
0           Chips and Fresh Tomato Salsa         1
1                                   Izze         1
2                       Nantucket Nectar         1
3  Chips and Tomatillo-Green Chili Salsa         1
4                           Chicken Bowl         2

#### 3. How to select the first 10 rows of the DataFrame?

In [6]:
first_10_rows = df.head(10)
first_10_rows

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",$10.98
6,3,1,Side of Chips,NaN,$1.69
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.75
8,4,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",$9.25
9,5,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",$9.25

#### 4. How to select rows where 'quantity' is greater than 1?

In [7]:
quantity_greater_than_1 = df[df['quantity'] > 1]
quantity_greater_than_1.head()

,order_id,quantity,item_name,choice_description,item_price
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
18,9,2,Canned Soda,[Sprite],$2.18
51,23,2,Canned Soda,[Mountain Dew],$2.18
135,60,2,Chicken Salad Bowl,"[Tomatillo Green Chili Salsa, [Sour Cream, Che...",$22.50
148,67,2,Steak Burrito,"[Tomatillo-Red Chili Salsa (Hot), [Rice, Chees...",$17.98

#### 5. How to select the 'item_price' for the item at index 5 using `.loc` and `.iloc`?

In [8]:
item_price_at_index_5_loc = df.loc[5, 'item_price']
print(f"Using .loc: {item_price_at_index_5_loc}")

item_price_at_index_5_iloc = df.iloc[5, df.columns.get_loc('item_price')]
print(f"Using .iloc: {item_price_at_index_5_iloc}")

Using .loc: $10.98
Using .iloc: $10.98

#### 6. How to select the 'item_name' and 'item_price' columns for rows where 'quantity' is 2?

In [9]:
item_name_price_quantity_2 = df[df['quantity'] == 2][['item_name', 'item_price']]
item_name_price_quantity_2.head()

              item_name item_price
4          Chicken Bowl    $16.98
18          Canned Soda     $2.18
51          Canned Soda     $2.18
135  Chicken Salad Bowl    $22.50
148       Steak Burrito    $17.98

#### 7. How to select all rows where 'item_name' is 'Chicken Bowl' and 'quantity' is 1?

In [10]:
chicken_bowl_quantity_1 = df[(df['item_name'] == 'Chicken Bowl') & (df['quantity'] == 1)]
chicken_bowl_quantity_1.head()

,order_id,quantity,item_name,choice_description,item_price
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",$10.98
13,7,1,Chicken Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$11.25
19,10,1,Chicken Bowl,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$8.75
26,13,1,Chicken Bowl,"[Roasted Chili Corn Salsa (Medium), [Pinto Bea...",$8.49
42,20,1,Chicken Bowl,"[Roasted Chili Corn Salsa, [Rice, Black Beans,...",$11.25

#### 8. How to select rows from index 10 to 15 (inclusive) for all columns using `.iloc`?

In [11]:
rows_10_to_15 = df.iloc[10:16]
rows_10_to_15

,order_id,quantity,item_name,choice_description,item_price
10,5,1,Chips and Guacamole,NaN,$4.45
11,6,1,Chicken Crispy Tacos,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",$8.75
12,6,1,Chicken Soft Tacos,"[Roasted Chili Corn Salsa, [Rice, Black Beans,...",$8.75
13,7,1,Chicken Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$11.25
14,7,1,Chips and Guacamole,NaN,$4.45
15,8,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39

#### 9. How to select the 'item_price' for the last 3 rows using `.tail()`?

In [12]:
item_price_last_3 = df['item_price'].tail(3)
item_price_last_3

4619    $11.25
4620     $8.75
4621     $8.75
Name: item_price, dtype: object

#### 10. How to check if any 'item_name' contains the word 'Salad'?

In [14]:
contains_salad = df['item_name'].str.contains('Salad').any()
contains_salad

np.True_