# Ex2 - Getting and Knowing your Data

This time we are going to pull data directly from the internet.
Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

### Step 1. Import the necessary libraries

In [1]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv).

In [2]:
data = pd.read_csv('https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv', sep='\t')

### Step 3. Assign it to a variable called chipo.

In [3]:
chipo = data

### Step 4. See the first 10 entries

In [4]:
chipo.head(10)

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",$10.98
6,3,1,Side of Chips,NaN,$1.69
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.75
8,4,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",$9.25
9,5,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",$9.25

### Step 5. What is the number of observations in the dataset?

In [5]:
# Solution 1
len(chipo)

4622

In [6]:
# Solution 2
chipo.shape[0]

4622

### Step 6. What is the number of columns in the dataset?

In [7]:
chipo.shape[1]

5

### Step 7. Print the name of all the columns.

In [8]:
chipo.columns

Index(['order_id', 'quantity', 'item_name', 'choice_description',
       'item_price'],
      dtype='object')

### Step 8. How is the dataset indexed?

In [9]:
chipo.index

RangeIndex(start=0, stop=4622, step=1)

### Step 9. Which was the most-ordered item?

In [10]:
chipo.item_name.value_counts().head(1)

item_name
Chicken Bowl    726
Name: count, dtype: int64

In [11]:
chipo.item_name.value_counts().head(1)
most_ordered_item = chipo.item_name.value_counts().head(1).index[0]
most_ordered_item

'Chicken Bowl'

### Step 10. For the most-ordered item, how many items were ordered?

In [12]:
chipo.query('item_name == @most_ordered_item').quantity.sum()

np.int64(761)

In [13]:
chipo.groupby('item_name')['quantity'].sum().sort_values(ascending=False).head(1)

item_name
Chicken Bowl    761
Name: quantity, dtype: int64

In [14]:
chipo.groupby('item_name').quantity.sum().max()

761

### Step 11. What was the most ordered item in the choice_description column?

In [15]:
most_ordered_item_choice_description = chipo.choice_description.value_counts().head(1)
most_ordered_item_choice_description

choice_description
[Diet Coke]    134
Name: count, dtype: int64

In [16]:
most_ordered_item_choice_description.index[0]

'[Diet Coke]'

### Step 12. How many items were orderd in total?

In [17]:
chipo.quantity.sum()

np.int64(4972)

### Step 13. Turn the item price into a float

#### Step 13.a. Check the item price type

In [18]:
chipo.item_price.dtype

dtype('O')

#### Step 13.b. Create a lambda function and change the type of item price

In [19]:
to_float = lambda x: float(x[1:-1])
chipo.item_price = chipo.item_price.apply(to_float)

In [20]:
chipo.head()

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,2.39
1,1,1,Izze,[Clementine],3.39
2,1,1,Nantucket Nectar,[Apple],3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98

#### Step 13.c. Check the item price type

In [21]:
chipo.item_price.dtype

dtype('float64')

### Step 14. How much was the revenue for the period in the dataset?

In [22]:
chipo.item_price.sum()

np.float64(34500.16)

### Step 15. How many orders were made in the period?

In [23]:
chipo.order_id.count()

np.int64(4622)

In [24]:
chipo.shape

(4622, 5)

In [25]:
chipo.order_id.nunique()

1834

### Step 16. What is the average revenue amount per order?

In [26]:
# Solution 1
chipo.groupby('order_id').item_price.sum().mean()

np.float64(18.811428571428568)

In [31]:
# Solution 2
chipo.item_price.sum()/chipo.order_id.nunique()

np.float64(18.811428571428575)

### Step 17. How many different items are sold?

In [28]:
chipo.item_name.nunique()

50