# Pokemon

### Introduction:

This time you will create the data.



### Step 1. Import the necessary libraries

In [1]:
import pandas as pd

### Step 2. Create a data dictionary that looks like the DataFrame below

In [2]:
data = {"evolution": ['Ivysaur', 'Charmeleon', 'Wartortle', 'Metapod'],
        "hp":[45, 39, 44, 45],
        "name":['Bulbasaur', 'Charmander', 'Squirtle', 'Caterpie'],
        "pokedex":['yes', 'no', 'yes', 'no'],
        "type": ['grass', 'fire', 'water', 'bug']}

### Step 3. Assign it to a variable called pokemon

In [3]:
pokemon = pd.DataFrame(data)
pokemon

    evolution  hp        name pokedex   type
0     Ivysaur  45   Bulbasaur     yes  grass
1  Charmeleon  39  Charmander      no   fire
2   Wartortle  44    Squirtle     yes  water
3     Metapod  45    Caterpie      no    bug

### Step 4. Ops...it seems the DataFrame columns are in alphabetical order. Place  the order of the columns as name, type, hp, evolution, pokedex

In [4]:
pokemon = pokemon[['name', 'type', 'hp', 'evolution', 'pokedex']]
pokemon

         name   type  hp   evolution pokedex
0   Bulbasaur  grass  45     Ivysaur     yes
1  Charmander   fire  39  Charmeleon      no
2    Squirtle  water  44   Wartortle     yes
3    Caterpie    bug  45     Metapod      no

### Step 5. Add another column called place, and insert what you have in mind.

In [6]:
pokemon['place'] = ['forest', 'ocean', 'lake', 'cave']
pokemon

/tmp/ipykernel_8234/644575280.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pokemon['place'] = ['forest', 'ocean', 'lake', 'cave']

         name   type  hp   evolution pokedex   place
0   Bulbasaur  grass  45     Ivysaur     yes  forest
1  Charmander   fire  39  Charmeleon      no   ocean
2    Squirtle  water  44   Wartortle     yes    lake
3    Caterpie    bug  45     Metapod      no    cave

### Step 6. Present the type of each column

In [8]:
pokemon.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   name       4 non-null      object
 1   type       4 non-null      object
 2   hp         4 non-null      int64
 3   evolution  4 non-null      object
 4   pokedex    4 non-null      object
 5   place      4 non-null      object
dtypes: int64(1), object(5)
memory usage: 324.0+ bytes

### BONUS: Create your own question and answer it.

Which Pokemon have an HP greater than 40?

In [9]:
pokemon[pokemon['hp'] > 40]

        name   type  hp  evolution pokedex   place
0  Bulbasaur  grass  45    Ivysaur     yes  forest
2   Squirtle  water  44  Wartortle     yes    lake
3   Caterpie    bug  45    Metapod      no    cave