# Ex1 - Filtering and Sorting Data

This time we are going to pull data directly from the internet.
Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

### Step 1. Import the necessary libraries

In [1]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv).

In [2]:
data = pd.read_csv("https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv", sep="\t")

### Step 3. Assign it to a variable called chipo.

In [3]:
chipo = data

In [4]:
chipo.head()

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98

### Step 4. How many products cost more than $10.00?

In [12]:
chipo['item_price'] = (chipo['item_price']).astype(str).str.replace('$', '').astype(float)

In [13]:
chipo.item_price

0        2.39
1        3.39
2        3.39
3        2.39
4       16.98
        ...
4617    11.75
4618    11.75
4619    11.25
4620     8.75
4621     8.75
Name: item_price, Length: 4622, dtype: float64

In [15]:
more_than_10 = (chipo['item_price'] > 10).sum()

In [17]:
more_than_10

np.int64(1130)

### Step 5. What is the price of each item?
###### print a data frame with only two columns item_name and item_price

In [20]:
pd.crosstab(chipo["item_name"],["item_price"])

col_0                                  item_price
item_name
6 Pack Soft Drink                              54
Barbacoa Bowl                                  66
Barbacoa Burrito                               91
Barbacoa Crispy Tacos                          11
Barbacoa Salad Bowl                            10
Barbacoa Soft Tacos                            25
Bottled Water                                 162
Bowl                                            2
Burrito                                         6
Canned Soda                                   104
Canned Soft Drink                             301
Carnitas Bowl                                  68
Carnitas Burrito                               59
Carnitas Crispy Tacos                           7
Carnitas Salad                                  1
Carnitas Salad Bowl                             6
Carnitas Soft Tacos                            40
Chicken Bowl                                  726
Chicken Burrito                               553
Chicken Crispy Tacos                           47
Chicken Salad                                   9
Chicken Salad Bowl                            110
Chicken Soft Tacos                            115
Chips                                         211
Chips and Fresh Tomato Salsa                  110
Chips and Guacamole                           479
Chips and Mild Fresh Tomato Salsa               1
Chips and Roasted Chili Corn Salsa             22
Chips and Roasted Chili-Corn Salsa             18
Chips and Tomatillo Green Chili Salsa          43
Chips and Tomatillo Red Chili Salsa            48
Chips and Tomatillo-Green Chili Salsa          31
Chips and Tomatillo-Red Chili Salsa            20
Crispy Tacos                                    2
Izze                                           20
Nantucket Nectar                               27
Salad                                           2
Side of Chips                                 101
Steak Bowl                                    211
Steak Burrito                                 368
Steak Crispy Tacos                             35
Steak Salad                                     4
Steak Salad Bowl                               29
Steak Soft Tacos                               55
Veggie Bowl                                    85
Veggie Burrito                                 95
Veggie Crispy Tacos                             1
Veggie Salad                                    6
Veggie Salad Bowl                              18
Veggie Soft Tacos                               7

### Step 6. Sort by the name of the item

In [21]:
pd.crosstab(chipo["item_name"],["item_price"]).sort_values("item_name")

col_0                                  item_price
item_name
6 Pack Soft Drink                              54
Barbacoa Bowl                                  66
Barbacoa Burrito                               91
Barbacoa Crispy Tacos                          11
Barbacoa Salad Bowl                            10
Barbacoa Soft Tacos                            25
Bottled Water                                 162
Bowl                                            2
Burrito                                         6
Canned Soda                                   104
Canned Soft Drink                             301
Carnitas Bowl                                  68
Carnitas Burrito                               59
Carnitas Crispy Tacos                           7
Carnitas Salad                                  1
Carnitas Salad Bowl                             6
Carnitas Soft Tacos                            40
Chicken Bowl                                  726
Chicken Burrito                               553
Chicken Crispy Tacos                           47
Chicken Salad                                   9
Chicken Salad Bowl                            110
Chicken Soft Tacos                            115
Chips                                         211
Chips and Fresh Tomato Salsa                  110
Chips and Guacamole                           479
Chips and Mild Fresh Tomato Salsa               1
Chips and Roasted Chili Corn Salsa             22
Chips and Roasted Chili-Corn Salsa             18
Chips and Tomatillo Green Chili Salsa          43
Chips and Tomatillo Red Chili Salsa            48
Chips and Tomatillo-Green Chili Salsa          31
Chips and Tomatillo-Red Chili Salsa            20
Crispy Tacos                                    2
Izze                                           20
Nantucket Nectar                               27
Salad                                           2
Side of Chips                                 101
Steak Bowl                                    211
Steak Burrito                                 368
Steak Crispy Tacos                             35
Steak Salad                                     4
Steak Salad Bowl                               29
Steak Soft Tacos                               55
Veggie Bowl                                    85
Veggie Burrito                                 95
Veggie Crispy Tacos                             1
Veggie Salad                                    6
Veggie Salad Bowl                              18
Veggie Soft Tacos                               7

### Step 7. What was the quantity of the most expensive item ordered?

In [29]:
#solution 1
chipo.groupby("item_name").max().sort_values("item_price", ascending=False).head(1)

,order_id,quantity,choice_description,item_price
item_name,,,,
Chips and Fresh Tomato Salsa,1790,15,NaN,44.25

In [35]:
#solution 2
chipo.sort_values("item_price", ascending=False).head(1)['quantity']

3598    15
Name: quantity, dtype: int64

### Step 8. How many times was a Veggie Salad Bowl ordered?

In [31]:
chipo.groupby("item_name").sum().loc["Veggie Salad Bowl", "quantity"]

np.int64(18)

In [38]:
chipo.item_name.value_counts()["Veggie Salad Bowl"]

np.int64(18)

Step 9. How many times did someone order more than one Canned Soda?

In [48]:
(chipo[chipo['item_name'] == "Canned Soda"]['quantity'] > 1).sum()

np.int64(20)